# Generated by Django 2.0.3 on 2020-01-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DaysOfweek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(blank=True, choices=[('sunday', 'sun'), ('monday', 'mon'), ('tuesday', 'tue'), ('wedsday', 'wed'), ('thrsday', 'thr'), ('friday', 'fri'), ('saturday', 'sat')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=20, null=True)),
                ('level', models.CharField(max_length=10, null=True)),
                ('flightNum', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('route', models.CharField(max_length=20, null=True)),
                ('dateFrom', models.DateTimeField(blank=True, null=True)),
                ('dateTo', models.DateTimeField(blank=True, null=True)),
                ('EOBT', models.TimeField(blank=True, null=True)),
                ('DesAirport', models.CharField(blank=True, max_length=10)),
                ('DepAirport', models.CharField(blank=True, max_length=10)),
                ('daysOfweek', models.CharField(blank=True, max_length=300)),
                ('delay', models.NullBooleanField(max_length=5)),
                ('change', models.NullBooleanField(max_length=5)),
                ('register', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='loggingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionName', models.CharField(max_length=10, null=True)),
                ('dateAndTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='typeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('family', models.CharField(max_length=20, null=True)),
                ('username', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('job', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
