# Generated by Django 2.0.3 on 2020-01-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='stripImage',
            field=models.ImageField(default='app1/static/strip.jpg', upload_to='media/'),
        ),
    ]
