# Generated by Django 2.0.3 on 2020-01-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_flight_stripimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='stripImage',
            field=models.ImageField(default='strip.jpg', upload_to='app1/image/'),
        ),
    ]
