# Generated by Django 2.0.3 on 2020-01-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200129_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='stripImage',
            field=models.ImageField(upload_to=''),
        ),
    ]
