# Generated by Django 2.0.3 on 2020-02-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200131_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='printed',
            field=models.NullBooleanField(max_length=5),
        ),
    ]
