# Generated by Django 2.0.3 on 2020-02-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_flight_printed'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='squack',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
