# Generated by Django 2.2.4 on 2019-10-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20190712_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=20, null=True)),
                ('level', models.CharField(max_length=10, null=True)),
                ('flightNum', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('route', models.CharField(max_length=20, null=True)),
                ('dateFrom', models.DateField(blank=True, verbose_name='Plan Date From')),
                ('EOBT', models.TimeField(blank=True)),
                ('DesAirport', models.CharField(blank=True, max_length=10)),
                ('DepAirport', models.CharField(blank=True, max_length=10)),
                ('DayofWeek', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
