# Generated by Django 2.0.3 on 2020-02-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20200218_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='squack',
            field=models.CharField(default='0000', max_length=20, null=True),
        ),
    ]
