# Generated by Django 2.0.3 on 2020-02-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20200218_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='stripImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
