# Generated by Django 2.2.4 on 2019-10-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20191012_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='DepAirport',
        ),
    ]
