# Generated by Django 2.2.4 on 2019-10-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_flight_depairport'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='DepAirport',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
