# Generated by Django 2.2.4 on 2019-10-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20191012_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='EOBT',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
