# Generated by Django 2.0.3 on 2020-03-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20200229_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='printingSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutesDiff', models.CharField(max_length=5, null=True)),
                ('printername', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
