# Generated by Django 2.2.4 on 2019-10-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20191012_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='companyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='typeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
