# Generated by Django 2.2.4 on 2019-10-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_companylist_typelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='DayofWeek',
            field=models.CharField(blank=True, choices=[('item1', 'sun'), ('item2', 'mon')], default=None, max_length=20),
        ),
    ]
