# Generated by Django 2.2.4 on 2019-10-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20191025_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='DayofWeek',
            field=models.CharField(blank=True, choices=[('1', 'sun'), ('2', 'mon'), ('3', 'tue'), ('4', 'wed'), ('5', 'thr'), ('6', 'fri'), ('7', 'sat')], default=None, max_length=20),
        ),
    ]
