# Generated by Django 2.2.4 on 2019-10-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20191026_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='dateTo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
