# Generated by Django 2.2.4 on 2019-10-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_auto_20191026_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOfweek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(blank=True, choices=[('1', 'sun'), ('2', 'mon'), ('3', 'tue'), ('4', 'wed'), ('5', 'thr'), ('6', 'fri'), ('7', 'sat')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='DayofWeek',
        ),
        migrations.AddField(
            model_name='flight',
            name='daysOfweek',
            field=models.ManyToManyField(blank=True, null=True, to='app1.DaysOfweek'),
        ),
    ]
