# Generated by Django 2.2.4 on 2019-10-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_auto_20191031_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysofweek',
            name='days',
            field=models.CharField(blank=True, choices=[('sunday', 'sun'), ('monday', 'mon'), ('tuesday', 'tue'), ('wedsday', 'wed'), ('thrsday', 'thr'), ('friday', 'fri'), ('saturday', 'sat')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='flight',
            name='daysOfweek',
        ),
        migrations.AddField(
            model_name='flight',
            name='daysOfweek',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
