# Generated by Django 2.2.4 on 2019-11-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_auto_20191031_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='delay',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='flight',
            name='daysOfweek',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
