# Generated by Django 2.2.4 on 2019-11-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_auto_20191115_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='change',
            field=models.BooleanField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='delay',
            field=models.BooleanField(blank=True, max_length=5, null=True),
        ),
    ]
