# Generated by Django 2.2.4 on 2019-11-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_auto_20191115_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='register',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
