# Generated by Django 2.0.3 on 2019-12-16 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_flight_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='change',
            field=models.NullBooleanField(max_length=5),
        ),
        migrations.AlterField(
            model_name='flight',
            name='dateFrom',
            field=models.DateField(blank=True, default=datetime.date(1111, 11, 11), null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='dateTo',
            field=models.DateField(blank=True, default=datetime.date(1111, 11, 11), null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='delay',
            field=models.NullBooleanField(max_length=5),
        ),
    ]
