# Generated by Django 2.0.3 on 2019-12-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_auto_20191216_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='dateFrom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='dateTo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
